### ISSUE TITLE
How can I build shape file described in section. 3

### ISSUE THREAD

**Issue by mashiro210** [filipematias23/FIELDimageR.Extra#1]
I tried to build shape file as you described in section. 3, however, menu button was not displayed in plot section on my Studio. How can I fix it?

![スクリーンショット 2023-08-16 20 41 12](https://github.com/filipematias23/FIELDimageR.Extra/assets/63339688/ed2221c8-b132-438e-9ead-3559348eb67d)

**Comment by filipematias23** [comment]
Hey there,

You are using fieldView() for visualization. To build grids you should use
the function fieldShape_render(). Try it and let us know… ok

Best,
Filipe

**Comment by mashiro210** [comment]
I misunderstood fieldShape_render(). Thank you!
